name: Testes de API e E2E

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # API - Instalar dependências
      - name: Instalar dependências da API
        run: npm install
        working-directory: ./Api

      # API - Rodar testes com Retry Manual
      - name: Rodar testes de API com Retry (Newman)
        run: |
          cd Api
          for i in 1 2 3; do
            echo "Tentativa $i de 3 para testes de API..."
            npx newman run gorest_collection.json \
              --env-var "token=${{ secrets.GOREST_TOKEN }}" \
              -r cli,htmlextra \
              --reporter-htmlextra-export reports/relatorio.html && break
            echo "Tentativa $i falhou. Tentando novamente..."
            sleep 5
          done

      # E2E - Instalar dependências
      - name: Instalar dependências do Cypress
        run: npm install
        working-directory: ./Cypress

      # E2E - Rodar testes com Retry Manual
      - name: Rodar testes E2E com Retry (Cypress)
        run: |
          cd Cypress
          for i in 1 2 3; do
            echo "Tentativa $i de 3 para testes E2E..."
            npx cypress run && break
            echo "Tentativa $i falhou. Tentando novamente..."
            sleep 5
          done
        env:
          CYPRESS_USER: ${{ secrets.CYPRESS_USER }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

      # Relatórios da API
      - name: Upload do Relatório de Testes da API
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes-api
          path: Api/reports/relatorio.html

      # Relatórios do Cypress
      - name: Upload dos Resultados do Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resultados-testes-cypress
          path: |
            Cypress/cypress/screenshots
            Cypress/cypress/videos
          if-no-files-found: ignore
