# Nome do fluxo de trabalho de Integração Contínua
name: Testes de API e E2E

# Gatilho (trigger): Este workflow será executado em cada push para a branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define os jobs (tarefas) a serem executados
jobs:
  run-all-tests:
    # Máquina virtual que será usada para executar os testes
    runs-on: ubuntu-latest

    # Passos (steps) que compõem o job
    steps:
      # 1. Clona o código do repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Node.js, necessário para Newman e Cypress
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- SEÇÃO DE TESTES DE API (NEWMAN) ---
      
      # 3. Instala as dependências da API
      - name: Instalar dependências da API
        run: npm install
        working-directory: ./Api

      # 4. Executa os testes de API com Newman (COM ATÉ 3 TENTATIVAS)
      - name: Rodar testes de API (Newman) com até 3 tentativas
        uses: nick-in-gns/action-retries@v3
        with:
          # Número máximo de tentativas (1 original + 2 retentativas)
          max_tries: 3
          # O comando que será executado e repetido em caso de falha
          command: npx newman run gorest_collection.json --env-var "token=${{ secrets.GOREST_TOKEN }}" -r cli,htmlextra --reporter-htmlextra-export reports/relatorio.html
        working-directory: ./Api

      # --- SEÇÃO DE TESTES E2E (CYPRESS) ---
      
      # 5. Instala as dependências do Cypress
      - name: Instalar dependências do Cypress
        run: npm install
        working-directory: ./Cypress

      # 6. Executa os testes do Cypress em modo headless (COM ATÉ 3 TENTATIVAS)
      - name: Rodar testes E2E (Cypress) com até 3 tentativas
        uses: nick-in-gns/action-retries@v3
        env:
          CYPRESS_USER: ${{ secrets.CYPRESS_USER }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
        with:
          # Número máximo de tentativas (1 original + 2 retentativas)
          max_tries: 3
          # O comando que será executado e repetido em caso de falha
          command: npx cypress run --browser chrome
        working-directory: ./Cypress
          
      # --- SEÇÃO DE UPLOAD DOS RELATÓRIOS (ARTIFACTS) ---

      - name: Upload do Relatório de Testes da API
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes-api
          path: Api/reports/relatorio.html
          
      - name: Upload dos Resultados do Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resultados-testes-cypress
          path: |
            Cypress/cypress/screenshots
            Cypress/cypress/videos
          if-no-files-found: ignore