# Nome do fluxo de trabalho de Integração Contínua
name: Testes de API e E2E

# Este workflow será executado em pushes ou pull requests na branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-all-tests:
    # Sistema operacional da máquina de execução
    runs-on: ubuntu-latest

    # Estratégia para repetir automaticamente em caso de falha
    strategy:
      fail-fast: false
      max-attempts: 3

    steps:
      # 🔁 Etapa 1: Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 🔧 Etapa 2: Configura Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Versão estável recomendada

      # 🧪 ETAPAS DE TESTES DE API (Newman)
      # --------------------------------------

      - name: Instalar dependências da API
        run: npm install
        working-directory: ./Api

      - name: Executar testes de API com Newman
        run: |
          npx newman run gorest_collection.json \
          --env-var "token=${{ secrets.GOREST_TOKEN }}" \
          -r cli,htmlextra \
          --reporter-htmlextra-export reports/relatorio.html
        working-directory: ./Api

      # 🌐 ETAPAS DE TESTES E2E (CYPRESS)
      # --------------------------------------

      - name: Instalar dependências do Cypress
        run: npm install
        working-directory: ./Cypress

      - name: Executar testes E2E com Cypress
        run: npx cypress run
        working-directory: ./Cypress
        env:
          CYPRESS_USER: ${{ secrets.CYPRESS_USER }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          # Adicione outras variáveis se necessário

      # 📦 UPLOAD DOS RELATÓRIOS (MESMO SE DER ERRO)
      # --------------------------------------

      - name: Upload do relatório HTML da API
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes-api
          path: Api/reports/relatorio.html

      - name: Upload dos vídeos e screenshots do Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resultados-testes-cypress
          path: |
            Cypress/cypress/screenshots
            Cypress/cypress/videos
          if-no-files-found: ignore
